# Generated by Django 5.1.5 on 2025-08-31 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_planthealthreport_confidence_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegetationIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_type', models.CharField(choices=[('NDVI', 'Normalized Difference Vegetation Index'), ('EVI', 'Enhanced Vegetation Index'), ('SAVI', 'Soil Adjusted Vegetation Index')], default='NDVI', max_length=10)),
                ('date', models.DateTimeField()),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('mean_value', models.FloatField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetation_indices', to='myapp.polygon')),
            ],
            options={
                'verbose_name': 'Vegetation Index',
                'verbose_name_plural': 'Vegetation Indices',
                'ordering': ['-date'],
            },
        ),
    ]
